---
- name: BIND file copy/backup
  hosts: localhost regulus
  gather_facts: no
  become: yes
  
  
  vars:
    fileSrc: "/etc/bind/"
    fileDst: "/var/tmp/"
  
  tasks:
    
    - name: tar bind files
      ansible.builtin.shell: 
        cmd: tar -czf {{ fileDst }}{{ inventory_hostname }}.bindBackup.tgz *
        chdir: "{{ fileSrc }}"
  