---
- name: BIND file copy/backup
  hosts: nameservers
  gather_facts: yes
  become: yes
  connection: local
  
  
  vars:
    fileSrc: "/etc/bind/"
    fileDst: "/var/tmp/"
    fileStore: "/media/thumb/"
    fileName: "{{ inventory_hostname }}-{{ ansible_date_time.date }}.bindBU.tgz"
  
  tasks:
    
    - name: tar bind files
      ansible.builtin.shell: 
        cmd: tar -czf "{{ fileStore }}""{{ fileName }}" *
        chdir: "{{ fileSrc }}"