---
- name: Docker info
  hosts: altair
  gather_facts: no
   
  tasks:
  
    - name: Show service status
      community.docker.docker_container_exec:
        container: webserver1
        command: /bin/bash -c "service --status-all"
      register: result

    - name: Print stdout
      debug:
        var: result.stdout