---
- name: Docker stack info
  hosts: altair regulus
  
  tasks:
    - name: show stack info
      community.docker.docker_stack_info:
      register: result
      
    - name: Print results 
      debug: 
        var: result.results