---
- name: Windows Info 
  hosts: windesk
  gather_facts: false
  roles:
  - role: jborean93.win_openssh
    opt_openssh_setup_service: True
  tasks:
   - name: run the setup facts
     ansible.builtin.setup: