---
- hosts: bigips
  tasks:
   - name: Collect all BIG-IP information
     bigip_device_info:
       gather_subset:
        - gtm-wide-ips
        - gtm-pools      
       provider: "{{ provider }}"
     register: output
     delegate_to: localhost
   - debug: var=output.ansible_facts.ansible_net_gtm_a_pools_name
       
   # - name: Copy output to file
     # copy:
       # content: "{{ output.ansible_facts | to_nice_json(indent=2) }}"
       # dest: "/var/tmp/{{ inventory_hostname }}_gtmInfo.json"
       
   # - name: Extract pools
     # copy:
       # content: "{{ output.ansible_facts.ansible_net_gtm_a_pools | to_nice_json(indent=2) }}"
       # dest: "/var/tmp/{{ inventory_hostname }}_gtmpools.json"
       
   # - name: Fetch results file
     # fetch:
       # src: /var/tmp/{{ inventory_hostname }}_gtmInfo.json
       # dest: /home/ansible/outputs/
       # flat: yes 