---
- name: Upload software iso file
  hosts: bigips
  gather_facts: no
  connection: local
  
  vars_prompt:
   - name: version
     prompt: "Version filename to upload BIGIP-16.1.3-0.0.12.iso"
     private: no
       
  tasks:
    - name: Upload image to the BIG-IP
      bigip_software_image:
        image: /var/tmp/{{ version }}  
        provider: "{{ provider }}"
      tags: upload
    
    - name: Install and active software
      bigip_software_install:
        image: "{{ version }}"
        state: installed
        volume: HD1.1
        provider: "{{ provider }}"
      tags: install