---
- name: Create docker networks
  hosts: dockerHosts
  gather_facts: no
  tasks:
  
    - name: Create vmnet2 docker network
      community.docker.docker_network:
        name: vmnet2
        driver: ipvlan
        driver_options: ipvlan_mode=l2
        ipam_config:
          - subnet: "{{ vmnet2Network }}"
            gateway: "{{ vmnet2GW }}"
            iprange: "{{ vmnet2Range }}" 
            aux_addresses:
              host1: "{{ vm2auxHost1 }}"
              host2: "{{ vm2auxHost2 }}" 