---
- name: Install Base
  hosts: servers
  gather_facts: no
  become: yes
  tasks:
        
   - name: apt update
     apt:
      update_cache: yes
    
   - name: install named (bind v9)
     apt: 
      name: bind9 
      state: present