---

- name: Play 1 Create Qkview
  gather_facts: no
  hosts: bigips
  connection: local
  tasks:
   - name: Create ucs file and download
     bigip_ucs_fetch:
       create_on_missing: yes
       src: "{{ device_hostname }}.ucs"
       dest: /tmp/{{ device_hostname }}.ucs
       provider: "{{ provider }}"
     tags: ucs
   
# - name: Copy ucs to backup dir 
  # gather_facts: no
  # hosts: regulus
  # connection: local
  # tasks:
   
   # - name: copy file
     # ansible.builtin.copy:
       # src: /var/tmp/dns1.bigipdevices.local.ucs
       # dest: /home/myers/backups/gtm/
       # remote_src: yes 
        
   
   # - name: remove ucs created in previous task
     # bigip_ucs:
       # ucs: "{{ device_hostname }}.ucs"
       # state: absent
       # provider: "{{ provider }}"
     # tags: ucs
     