---
- name: Create ucs backup and send it to backup storage
  gather_facts: yes
  hosts: bigips
  connection: local
  
  vars: 
    ucs_name: "{{ inventory_hostname }}-{{ ansible_date_time.date }}.ucs"
  
  tasks:
   - name: Create ucs file and download
     bigip_ucs_fetch:
       create_on_missing: yes
       src: "{{ ucs_name }}"
       dest: /var/tmp/{{ ucs_name }}
       provider: "{{ provider }}"
     
   - name: remove ucs from F5
     bigip_ucs:
       ucs: /var/local/ucs/{{ ucs_name }}
       state: absent
       provider: "{{ provider }}"

   - name: scp to regulus
     shell:
       cmd: scp -i .ssh/id_rsa /var/tmp/*.ucs 10.0.1.150:backups/
     delegate_to: localhost
    
   - name: remove ucs on local machine.
     file:
       path: /var/tmp/{{ ucs_name }}
       state: absent