---
- name: Gather GTM iQuery data
  hosts: bigips
  gather_facts: yes
  connection: local
  tasks: 
    - name: tmsh show gtm ...
      bigip_command:
        commands: 
         - show gtm wideip
         - show gtm pool
         - show gtm server virtual-servers
        wait_for:
          - result[0] contains offline
          - result[1] contains offline
          - result[2] contains timeout
          
        provider: "{{ provider }}"      
      register: cmdOut
    - debug: var=cmdOut.stdout_lines